version: "3.8"
services:
  mysql-stad:
    image: mysql:latest
    container_name: mysql-stad
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: stad
      MYSQL_ROOT_HOST: '%'
  mysql-stad-alert:
    image: mysql:latest
    container_name: mysql-stad-alert
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: stad
      MYSQL_ROOT_HOST: '%'
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"