cloud:
  aws:
    credentials:
      access-key: AKIA47CRZ7OMDBYL7VOR
      secret-key: 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
jwt:
  secret-key: c29ydGJyb2tlYXJyb3dmZWV0cmF0aGVybWFnaWNleHBsYW5hdGlvbmRhaWx5cmF0aGUGxyamVvYW9yb3JodG9kZ2
api:
  kakaoMap:
    key: 6018e4288bb8a7c8a9b8079f62ed442c
  naver:
    id: 0wINWpGSHxF5S7d5F18g
    secret: XQfurljqD2